### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by rvolosatovs** [rvolosatovs/docker-protobuf#67]
#### Summary

Add Kotlin support. Refs https://github.com/TheThingsNetwork/api/issues/43

#### How do you propose to implement this?

Investigate https://github.com/streem/pbandk

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by rvolosatovs** [comment]
@jpmeijers perhaps you would be interested in contributing to this?
You can see some examples:
- https://github.com/TheThingsIndustries/docker-protobuf/pull/64
- https://github.com/TheThingsIndustries/docker-protobuf/pull/49

**Comment by strophy** [comment]
I researched this for a while and got the build and resulting binary working fine, but I got stuck running it because our target container runs as root, and the way the Kotlin file is made executable using Spring Boot means it will always output a warning if it runs as root: https://github.com/streem/pbandk/issues/73

@rvolosatovs are you familiar with `gosu` or `su-exec`? Do you think it makes sense to change our target image to use an unprivileged user to run `protoc`? We could probably create a user in an entrypoint and set it to the same permissions as the mounted workdir [like this](https://stackoverflow.com/questions/23544282/what-is-the-best-way-to-manage-permissions-for-docker-shared-volumes/29799703#29799703)? We need to avoid making it a breaking change when doing this, for users that don't set a workdir...
